### ISSUE TITLE
object 'as.integer64' of mode 'function' was not found

### ISSUE THREAD

**Issue by dalamar66** [ggrothendieck/sqldf#14]
Hi,

I'm getting the following error,

> Error in get(as.character(FUN), mode = "function", envir = envir) : 
>   object 'as.integer64' of mode 'function' was not found

When I query a csv file, the column that gives the issue, can be visualized from RStudio without problems, it shows figures like: 4.611208e-314 when the file contains 9333158264 in that position, not sure if this is an issue with fread when reading the file itself, still sqldf shouldn't crash correct? 

The query that crashes it is simple select * from the data table.

This column appears as Class 'integer64' when I select other columnns there is no error.

**Comment by ggrothendieck** [comment]
Need a reproducible example.

**Comment by krlmlr** [comment]
Which version of RSQLite were you using?

**Comment by dalamar66** [comment]
Apologies for the late reply,

After installing the package bit64 the issue was solved.
install.packages("bit64")
