### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by krlmlr** [ggrothendieck/sqldf#15]
Could you please release to CRAN in the next few weeks? I'm removing compatibility code from RSQLite (https://github.com/rstats-db/RSQLite/issues/188), because this makes the package slightly less compatible with the DBI spec. If you add RSQLite (>= 1.1-2) to your Imports or Suggests, non-syntactic column names should behave correctly with SQLite.

**Comment by ggrothendieck** [comment]
0.4-11 addresses this

**Comment by krlmlr** [comment]
Thanks a lot, and sorry for the inconvenience. I believe that a cleaner interface for SQLite will pay off in the end.
