### ISSUE TITLE
Mysql, why not creating temporary tables?

### ISSUE THREAD

**Issue by lrob** [ggrothendieck/sqldf#16]
Hi, 
I was wondering why the package, when using the MySQL driver, instantiates R data frames as permanent tables and not as temporary tables. Wouldn't it be more convenient? 

I'm asking because I've written some code that is run by multiple users. Since I added some line using the sqldf function, people cannot anymore concurrently execute the code.

Thanks
Roberto

**Comment by ggrothendieck** [comment]
Use `dbname = tempfile()` argument to `sqldf` and then each person will be using a different database.

**Comment by lrob** [comment]
Thanks, but I cannot use a different database for each person running the code. Thy must use an existing database and cannot create one.
