### ISSUE TITLE
Select from Dual?

### ISSUE THREAD

**Issue by tres-pitt** [ggrothendieck/sqldf#17]
is it possible to select from dual? Specifically I need to use the MONTHS_BETWEEN function, as I haven't been able to find any R package that replicates its math! The sql is `SELECT MONTHS_BETWEEN 
   (TO_DATE('10-24-2017','MM-DD-YYYY'),
    TO_DATE('04-23-2014','MM-DD-YYYY') ) "Months"
    FROM DUAL;`

Sorry if this isn't an issue, it could be an awesome feature request. The current output is `error in statement: no such table: DUAL`. Searching 'dual' in the pdf didn't show me anything useful. thanks for your great work!!

**Comment by ggrothendieck** [comment]
This is not an appropriate use of issues.

(The H2 backend to sqldf has the `datediff` function which can compute the number of months between two dates. )
