### ISSUE TITLE
Integration sqldf() with R functions

### ISSUE THREAD

**Issue by joaoplm** [ggrothendieck/sqldf#19]
Hi, my name is João Paulo I am a master's student in the course of  omputer science. 

I intend to create a package for the R that makes the SQL language commands available for use. I know that sqldf() already execute SQL commands within R. However, these commands require querys to be passed as a string. I wish SQL commands could be used more naturally like the native R functions.

What I want to do is for example:  Select cor(df.a,df.b,df.c) from dataframe df.  In this case cor() is the native R function for correlation. This way i could integrate the R functions with SQL.

Do you have any idea of how can I do that? Is this possible??

**Comment by ggrothendieck** [comment]
dplyr can work with an SQL backend.
