### ISSUE TITLE
weird circumstance where ORDER BY changes the column type

### ISSUE THREAD

**Issue by ajdamico** [ggrothendieck/sqldf#2]
i assume there's nothing you can/will do about this weird circumstance, just wanted to run it by you in case i'm wrong.  thank you for sqldf, i have been using it daily for years.

	library(sqldf)

	y <- structure(list(size = c(1L, 1L, 2L, 2L), diff = c(NA, NA, 1, NA)) , .Names = c("gb","diff"), row.names = 1:4, class = "data.frame")

	sapply(sqldf("select sum(diff) , gb from y group by gb"),class)[1]

	sapply(sqldf("select sum(diff) , gb from y group by gb ORDER BY gb desc"),class)[1]

**Comment by ggrothendieck** [comment]
It has a heuristic that will set the class on any output column to be the same class as an input column of the same name so this would fix it:

```r
str(y)
## 'data.frame':   4 obs. of  2 variables:
##  $ gb  : int  1 1 2 2
##  $ diff: num  NA NA 1 NA

out1 <- sqldf("select sum(diff) diff, gb from y group by gb")
str(out1)
## 'data.frame':   2 obs. of  2 variables:
##  $ diff: num  NA 1
##  $ gb  : int  1 2

out2 <- sqldf("select sum(diff) diff, gb from y group by gb ORDER BY gb desc")
str(out2)
## 'data.frame':   2 obs. of  2 variables:
## $ diff: num  1 NA
## $ gb  : int  2 1
```

**Comment by ajdamico** [comment]
that makes perfect sense.  thank you again!!
