### ISSUE TITLE
full join

### ISSUE THREAD

**Issue by JCwinning** [ggrothendieck/sqldf#22]
Error in result_create(conn@ptr, statement) : 
  RIGHT and FULL OUTER JOINs are not currently supported

May I know how to do full join by using sqldf package ? will it function be available in the near future ?

**Comment by jangorecki** [comment]
if you use sqlite backend then it is sqlite issue, not sqldf.

**Comment by ggrothendieck** [comment]
sqldf is a front end to 4 different database systems so you get whatever the backend you are using provides.  PostgreSQL, which is one of the supported backend databases, does support these features.  If you want to stick with the default SQLite then google for *sqlite full join* and *sqlite right join* for workarounds.
