### ISSUE TITLE
run sql query with R's data.frame.object

### ISSUE THREAD

**Issue by jasperDD** [ggrothendieck/sqldf#26]
I have the dataset df

and i want to run on it sql query

df=sqldf("with cte as (
  Select *,datePart(WEEKDAY,Dt) as WeekDay,
  PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY SaleCount) Over (partition by ItemRelation, DocumentNum, DocumentYear) as PERCENTILE,
  avg(SaleCount) over (Partition by ItemRelation, DocumentNum, DocumentYear,datePart(WEEKDAY,Dt), IsPromo) as AVG_WeekDay
  From df)
Update a 
Set SaleCount = cte.AVG_WeekDay
From CTE
join df a 
on a.Dt = cte.dt
and a.ItemRelation=cte.ItemRelation 
and a.DocumentNum = cte.DocumentNum 
and a.DocumentYear = cte.DocumentYear 
and a.ispromo = cte.ispromo
Where CTE.PERCENTILE < CTE.SaleCount
and datePart(WEEKDAY,CTE.Dt) < 5
and CTE.ispromo = 0 ;
         Select * from df")

when i run sql query on this dataframe (df) i get the error

Error in rsqlite_send_query(conn@ptr, statement) : near "(": syntax error

How can i correct run this query. Notice: i work not from sql, but i need use sql query on R's dataframe object. Anybody, please help.

**Comment by ggrothendieck** [comment]
This is a question about your code, not an issue with the sqldf package. 

Your SQL statement is not valid sqlite and that is the causing the error.  Use a different backend and make sure that your SQL syntax conforms to the backend chosen. sqldf support sqlite, h2, mysql and postgresql.  See ?sqldf and the github home page for more info.  If you want to use partition ... over ... then you will want to use postgresql but will need to modify your query to conform to postgresql SQL syntax.
