### ISSUE TITLE
Return row_names as the row.names of the data.frame.

### ISSUE THREAD

**Issue by abalter** [ggrothendieck/sqldf#28]
When `row.names=T`, if the query contains `row_names` as a returned field, rather than returning a column called `row_names`, have `row_names` be the actual rownames of the returned dataframe.

That totally sounds like something engineered to be convoluted, but I think you can get what I'm talking about. 

**Example:**

_table_df_

| actual rownames | A | B |
|--------------------|---|-- |
| shaggy                 | 1 | p |
| scooby                 | 2 | q |
| velma                   | 3 | r |

    new_table = sqldf(row.names=T, "select row.names, B where A<3")

should return

| actual rownames | B |
|--------------------|-- |
| shaggy                 | p |
| scooby                 | q |

and NOT

| row_names          | B |
|--------------------|-- |
| shaggy                 | p |
| scooby                 | q |

**Comment by ggrothendieck** [comment]
It already does that.

```
rownames(BOD) <- letters[1:6]
sqldf("select * from BOD", row.names = TRUE)
##   Time demand
## a    1    8.3
## b    2   10.3
## c    3   19.0
## d    4   16.0
## e    5   15.6
## f    7   19.8
```

**Comment by abalter** [comment]
Hmmm. Not sure what was going on, but somehow  I ended up with a column called `row_names` that was then conflicting with, well, `row_names`.

I'm also confused about this error:

```
> a = data.frame(A=c(1,2,3), B=c('a','b','c'))
> rownames(a) = c('aaa','bbb','ccc')
> b = data.frame(C=c(10,20,30), D=c('p','q','r'))
> rownames(b) = c('ccc','bbb','aaa')
> 
> sqldf(row.names=T, "select * from a inner join b on a.row_names = b.row_names")
    A B  C D
aaa 1 a 30 r
bbb 2 b 20 q
ccc 3 c 10 p
Warning message:
In sqldf(row.names = T, "select * from a inner join b on a.row_names = b.row_names") :
  ambiguity regarding row names: row_namesambiguity regarding row names: row_names
```

Also, the `method` option looks super useful. I couldn't find an explicit description in the docs, but from the examples it looks like basically a post-processor. 

Fantastic package. A great amount of the time, sql is much more direct and easy to understand than data.frame and data.table methods.

**Comment by ggrothendieck** [comment]
The warning is due to multiple columns called `row_names`.

**Comment by abalter** [comment]
I'm confused because there are no columns called `row_names`. I'm just joining _on_ the `rownames`. What is the right way to do that?
