### ISSUE TITLE
Pointless check for . in `backquote.maybe`

### ISSUE THREAD

**Issue by hannesmuehleisen** [ggrothendieck/sqldf#3]
The check 
`if (regexpr(".", nam, fixed = TRUE)) {`
will always return `TRUE`, even if `nam` does not contain `.`.
Suggest
`if (regexpr(".", nam, fixed = TRUE) > 0) {`

https://github.com/ggrothendieck/sqldf/blob/25d9a903b6c4f09493ca1ec5c1101d957df70154/R/sqldf.R#L31

**Comment by krlmlr** [comment]
The entire function is obsolete with RSQLite > 1.0.
