### ISSUE TITLE
sqldf unable to handle labelled data

### ISSUE THREAD

**Issue by oljees** [ggrothendieck/sqldf#32]
Fantastic package, thanks!
For data imported with haven that builds some data.frames with labelled attributes, or any other data.frame with labels added, sqldf is unable to run select queries on labelled columns.  It returns the error

`Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'as.labelled' of mode 'function' was not found`

EXAMPLE:
library(labelled)
v <- labelled(c(1,2,2,2,3,9,1,3,2,NA), c(yes = 1, no = 3, "don't know" = 8, refused = 9))
y<-labelled(c(1,1,1,2,3,9,1,3,2,NA), c(yes = 1, no = 3, "don't know" = 8, refused = 9))
z<-data.frame(v,y)
sqldf("select * from z")
library(sjlabelled)
z<-remove_all_labels(z)
sqldf("select * from z")

So the only way to run sqldf on labelled objects is to remove labels first.  Is it possible to fix this so we can use sqldf on labelled data.frames?

cheers!

**Comment by oljees** [comment]
I have just seen the method="raw" option which allows queries to work on labelled data, apologies!

**Comment by ggrothendieck** [comment]
You can also use the `method` argument to define your own transformations.  See ?sqldf
