### ISSUE TITLE
Possible to join to other tables in database?

### ISSUE THREAD

**Issue by tsykes** [ggrothendieck/sqldf#34]
I was able to join R data frames using sqldf but is it possible to join a data frame to a large database table that already exists in the database with a single SQL statement? I've been doing this by writing my data frame to the database and using RPostgreSQL to read in the joined dataset back and then dropping the table. It would be handy if all table table references in a join didn't have to be data frames.

**Comment by ggrothendieck** [comment]
This currently only works with the SQLite backend.  See Example 9 at  https://github.com/ggrothendieck/sqldf
