### ISSUE TITLE
sqldf & SELECT Query

### ISSUE THREAD

**Issue by sdusa** [ggrothendieck/sqldf#37]
I am doing a SELECT query from a table in SQL Server using sqldf. The query result is grouped by count of a specific field. If the count field has NULL values, these seem to get dropped from the result. , even `though` na.rm=TRUE is specified in R. I will provide more data if needed.

`SELECT CustomerID, OrderType FROM table GROUP BY CustomerID ORDER BY COUNT(*) DESC`

**Comment by ggrothendieck** [comment]
sqldf does not work with SQL Server.
