### ISSUE TITLE
Help using field.types with read.csv.sql

### ISSUE THREAD

**Issue by michaeld1015** [ggrothendieck/sqldf#39]
Trying to use field.types with read.csv.sql, took a guess using something like this...

`field.types = list(names=c("name1", "name2"), contents=("TEXT", "DATETIME"))`

I'm maybe reading into the documentation too literally but wanted to take a stab at it and get it working ASAP.

Am I better off using colClasses?

Reason for doing this is read.csv.sql is reading in columns and not parsing the data types correctly.

**Comment by ggrothendieck** [comment]
Please read ?read.csv.sql
