### ISSUE TITLE
Using PostgreSQL driver requires a connection even if dbname = ":memory:"

### ISSUE THREAD

**Issue by Jesse-Kerr** [ggrothendieck/sqldf#42]
I want to run a SQL query on a table in memory in R. The query uses this function `regexp_split_to_array` which is in postgreSQL but not in SQLite. 

My understanding is that if you set the `dbname = ":memory:"`, the query will not need a connection -- however, it does fail saying that it is unable to connect.

```
library(sqldf)
df <- tibble(
    A = c(1, 2, 3))

# works
sqldf::sqldf(
    x = 
        "SELECT *
        FROM df", 
    drv = "SQLite"
)

# doesn't work
sqldf::sqldf(
    x = 
        "SELECT *
        FROM df", 
    drv = "PostgreSQL", 
    dbname = ":memory:"
)
```

If I supply a PostgreSQL connection, it fails cryptically:
```
sqldf::sqldf(
    x = 
        "SELECT *
        FROM df", 
    drv = "PostgreSQL", 
    dbname = ":memory:", 
    connection = con
)

Error in dbPreExists && !overwrite : invalid 'x' type in 'x && y'
```

Thanks for your help, sorry if I am having any misunderstandings.

**Comment by ggrothendieck** [comment]
:memory: is strictly for SQLite.  PostgreSQL does not support in memory databases,
