### ISSUE TITLE
Cannot download R package sqldf

### ISSUE THREAD

**Issue by SandTr** [ggrothendieck/sqldf#43]
**When trying to download/install de R package "sqldf" within RStudio I get this message:**
Error in download.file(url, destfile, method, mode = "wb", ...) : cannot open URL 'https://mran.microsoft.com/snapshot/2020-07-16/bin/windows/contrib/4.0/sqldf_0.4-11.zip'

**When trying to download it straight from the website I get this message:**
ICAP Error (icap_error) An error occurred while performing an ICAP operation: Blocked file extension detected; File: sqldf_0.4-11.zip; Sub File: ; Vendor: Symantec; Engine version: 7.0.0.158; Pattern version: 20210618.007.; Pattern date: 2021/06/18 12:25:44 There could be a network problem, the ICAP service may be misconfigured, or the ICAP server may have reported an error.

**Comment by ggrothendieck** [comment]
I have no trouble downloading that file from that site. This is a network or permissions problem on your end. Has nothing to do with sqldf.
