### ISSUE TITLE
default behavior of eol?

### ISSUE THREAD

**Issue by r2evans** [ggrothendieck/sqldf#44]
If I write a unix-y csv file on windows, then `read.csv.sql` fails while `read.csv` does not:

Saved as `quux.csv` (manually, not using `write.csv` or such):

```
quux,bar
1,100
2,200
```

Code:

```r
read.csv("quux.csv")
#   quux bar
# 1    1 100
# 2    2 200
sqldf::read.csv.sql("quux.csv", sql="select * from file")
# [1] quux bar 
# <0 rows> (or 0-length row.names)
system("unix2dos quux.csv")
# unix2dos: converting file quux.csv to DOS format...
# [1] 0
sqldf::read.csv.sql("quux.csv", sql="select * from file")
#   quux bar
# 1    1 100
# 2    2 200
```

An alternative fix is to specify `eol=`:

```r
system("dos2unix quux.csv")
# dos2unix: converting file quux.csv to Unix format...
# [1] 0
sqldf::read.csv.sql("quux.csv", sql="select * from file")
# [1] quux bar 
# <0 rows> (or 0-length row.names)
sqldf::read.csv.sql("quux.csv", sql="select * from file", eol = "\n")
#   quux bar
# 1    1 100
# 2    2 200
```

I know that `?read.csv.sql` says

```
# might need to specify eol= too depending on your system
```

Is this the reason for that comment in the example code? Is it known why `read.csv` works and this does not?

**Comment by ggrothendieck** [comment]
If you are on Windows it defaults to Windows line endings but eol is there to give you a way out.

**Comment by r2evans** [comment]
I understand, but that's kind of my point: `read.csv` will read a CSV in either format on either OS without need for intervention; `read.csv.sql` requires me to know a priori what type of file is being passed (in programmatic usage). While there are relatively trivial mechanisms to do that externally, perhaps it would be good to have an automatic eol-determination within `read.csv.sql`.

I don't consider this a bug, more of a corner-case refinement. Thanks for listening :-)

**Comment by ggrothendieck** [comment]
This depends on RSQLite which may depend on SQLite for this functionality it should be fixed there, not in sqldf.

**Comment by r2evans** [comment]
Good point, I incorrectly assumed the location of `eol=` use. Thank you!
